{{- range $realm := .Values.realms }}
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: realm-{{ $realm.name }}
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    realm: {{ $realm.name }}
    enabled: true
    clients:
      - name: {{ $realm.name }}
        enabled: true
        clientId: {{ $realm.name }}
        secret: "{{ $realm.clientSecret }}"
        protocol: openid-connect
        clientAuthenticatorType: client-secret
        standardFlowEnabled: true
        frontchannelLogout: true
        rootUrl: "https://{{ $realm.name }}.{{ $.Values.hostname }}"
        redirectUris:
          - "https://{{ $realm.name }}.{{ $.Values.hostname }}/*"
    users:
      {{- range $user := $realm.users }}
      - id: {{ $user.username }}
        enabled: true
        username: {{ $user.username }}
        credentials:
          - type: password
            value: "{{ randAlphaNum 20 }}"
        firstName: {{ $user.first_name }}
        lastName: {{ $user.last_name }}
        email: {{ $user.email }}
        emailVerified: true
      {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http-production
  name: reverse-proxy-{{ $realm.name }}
spec:
  gatewayClassName: traefik
  listeners:
    - name: websecure
      protocol: HTTPS
      port: 8443
      hostname: {{ $realm.name }}.{{ $.Values.hostname }}
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - group: core
            kind: Secret
            name: tls-{{ $realm.name }}-{{ $.Values.hostname | replace "." "-" }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: reverse-proxy-{{ $realm.name }}-traefik-oidc-auth
spec:
  plugin:
    traefik-oidc-auth:
      Secret: "{{ randAlphaNum 32 }}"
      Provider:
        Url: https://keycloak.{{ $.Values.hostname }}/realms/{{ $realm.name }}
        ClientId: {{ $realm.name }}
        ClientSecret: "${CLIENT_SECRET_{{ $realm.name | upper }}}"
      Scopes: [ "openid", "profile", "email" ]
      Headers:
        - Name: Authorization
          Value: "{{`Bearer {{ .accessToken }}`}}"
      BypassAuthenticationRule: Path(`/manifest.json`)
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: reverse-proxy-{{ $realm.name }}
spec:
  parentRefs:
    - name: reverse-proxy-{{ $realm.name }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: reverse-proxy-{{ $realm.name }}-traefik-oidc-auth
      backendRefs:
        - name: httpbin
          port: 80
{{- end }}
