apiVersion: v1
kind: Secret
metadata:
  name: client-secrets
stringData:
{{- range $realm, $clientSecret := .Values.clientSecrets }}
  CLIENT_SECRET_{{ $realm | upper }}: {{ $clientSecret | quote }}
{{- end }}
